name: tzgrid
version: '0.0.1'
summary: Display a grid of times to help with timezone math.
description: |
  Display a grid of times to help with timezone math.

grade: stable
confinement: strict

apps:
  tzgrid:
    # see: http://pad.lv/1576411
    command: env LC_ALL=C.UTF-8 tzgrid

parts:
  tzgrid:
    plugin: python
    python-version: python3
    source: .
    requirements: requirements.txt
  examples:
    plugin: dump
    source: ./examples
  data:
    plugin: dump
    source: ./data
